### ISSUE TITLE
How to sample lighting

### ISSUE THREAD

**Issue by BlueWinters** [GhostCai/PortraitRelighting#2]
greate work!!!!

I wonder to konw, how to get the value in `examples/example_lightings.npy`

**Comment by GhostCai** [comment]
Hi, thanks for your interest in this work!

The example lighting values were extracted using DPR on [FFHQ](https://github.com/NVlabs/ffhq-dataset) images. You can sample lighting values from portrait images by using the `WrapperLightingEstimator` class in `third_party/wrapper.py` from this repo. For more details on DPR, you might also check out the [original repository](https://github.com/zhhoper/DPR).

Hope this helps, and feel free to reach out if you have more questions!
