### ISSUE TITLE
Requirement.txt had failed Install in Ubuntu18.04.6

### ISSUE THREAD

**Issue by Daliuq** [GhostCai/PortraitRelighting#3]
other environment
cuda 12.4
python 3.10.15
gcc 11.4.0
pytorch not be installed
Is is can't run in Ubuntu 18?
with a very long error message
![image](https://github.com/user-attachments/assets/795a39c6-9400-4d1d-98b4-f4a2122c02e4)
![image](https://github.com/user-attachments/assets/b522377c-5dbe-45c0-8fce-25f049835bd6)
![image](https://github.com/user-attachments/assets/e0677eb3-a173-42a7-8ed9-732c0246bb59)
![image](https://github.com/user-attachments/assets/711724a9-f5db-446d-bf72-1e7335b89f42)

**Comment by GhostCai** [comment]
Hi there! I’m not certain if it works on Ubuntu 18, but it should be compatible. The issue appears to be related to a non-Python compilation error with the pyshtools library. Could you try removing pyshtools from requirements.txt and see if that resolves the issue?

**Comment by Daliuq** [comment]
OK，but there is anthony error in installing Pillow-simd，I’m trying to install  Pillow to replace it。

I am still installing the environment. If there are any issues, I will contact you again

**Comment by Daliuq** [comment]
I‘m successed . 
first delete pillow-simd and pyshtools in requirement.txt,Then install pillow-simd without jpeg supporting，and intall pyshtools with conda
