### ISSUE TITLE
How to gen cropped video frames and corresponding camera parameters

### ISSUE THREAD

**Issue by VSycx** [GhostCai/PortraitRelighting#4]
For the following two pre-requirements:
  Cropped video frames in examples/video/cropped/
  Corresponding camera parameters in examples/video/camera/
how do i gen them for any given video?
Is the function **reconstruct_image** outputs the correct crop image and camera parameters?
Cheers

**Comment by GhostCai** [comment]
Hi! We noticed that the camera parameters for videos are often quite inconsistent between frames causing flickering, so we apply exponential smoothing to the detected keypoints, as discussed in the supplementary material. To implement this, you can modify the `keypoints = eg3d_detect_keypoints(img_pil)` line inside `cropposer.wild2all`, adding smoothing to the detected keypoints. No other code changes are required.

I recommend experimenting with either average smoothing or exponential smoothing, adjusting the smoothing strength based on your video. For example, if the face exhibits large movements, you might want to use lower smoothing strength to maintain better alignment. On the other hand, for subtle movements, a higher smoothing strength can help achieve smoother camera parameters.

**Comment by VSycx** [comment]
got it，thanks for the great work~

**Comment by GhostCai** [comment]
We’re glad you found it helpful. Let us know if you have any further questions or suggestions!
