### ISSUE TITLE
如何使用自己准备的例子

### ISSUE THREAD

**Issue by zyhsweety** [GhostCai/PortraitRelighting#6]
作者您好，我成功的部署了您的代码并跑通了example.py文件，但当我想用自己准备的输入视频进行测试的时候却发现好像没有对视频帧处理相关的的代码，准确来说是我不知道如何生成examples/video/camera/*.npy系列的文件，不知道是不是我没找对，希望作者能帮我指出，万分感谢

**Comment by GhostCai** [comment]
你好～需要用[EG3D](https://github.com/NVlabs/eg3d/tree/main/dataset_preprocessing/ffhq)对FFHQ的预处理方式对视频逐帧进行处理，并对keypoints加平滑，逐帧处理可以参考example.py中的cropposer.wild2all，返回的["cam"]就是所需的camera/*.npy，也可以参考这个issue： #4 

此外，虽然模型也能处理轻微的图像不对齐，但还是建议将视频重新裁剪以获得更好的结果，也就是用返回的["img_cropped"]作为输入，而不是直接输入视频

**Comment by zyhsweety** [comment]
好的，谢谢作者解答
